trigger:
  - main

pr: none

pool:
  vmImage: windows-latest

stages:
  - stage: buildAndTest
    displayName: Build & Test
    jobs:
      - job:
        displayName: dotnet build/test/publish
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: 'UmbracoProject/UmbracoProject.csproj'
          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              arguments: '--collect:"XPlat Code Coverage" --logger trx'
              command: 'test'
              projects: '**/*.Tests.csproj'
          - task: PublishTestResults@2
            displayName: 'publish test results'
            inputs:
              searchFolder: $(Agent.TempDirectory)
              testResultsFiles: '**/*.trx'
              testRunner: NUnit
          - task: reportgenerator@5
            displayName: 'merge code coverage reports'
            inputs:
              reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
              reporttypes: 'Cobertura'
              targetdir: '$(Pipeline.Workspace)/coverlet'
              verbosity: 'Verbose'
          - task: PublishCodeCoverageResults@1
            displayName: 'publish code coverage results'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Pipeline.Workspace)/coverlet/Cobertura.xml'
