trigger: none

pr:
  branches:
      include:
          - main

pool:
  vmImage: windows-latest

stages:
  - stage: buildAndTest
    displayName: Build & Test
    jobs:
      - job:
        displayName: dotnet build/test/publish
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: 'UmbracoProject/UmbracoProject.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              arguments: '--collect:"XPlat Code Coverage" --logger trx'
              command: 'test'
              projects: '**/*.Tests.csproj'
          - task: PublishTestResults@2
            displayName: 'publish test results'
            inputs:
              searchFolder: $(Agent.TempDirectory)
              testResultsFiles: '**/*.trx'
              testRunner: VSTest
          - task: reportgenerator@5
            displayName: 'merge code coverage reports'
            inputs:
              reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
              reporttypes: 'Cobertura'
              targetdir: '$(Pipeline.Workspace)/coverlet'
              verbosity: 'Verbose'
          - task: PublishCodeCoverageResults@1
            displayName: 'publish code coverage results'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Pipeline.Workspace)/coverlet/Cobertura.xml'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              arguments: '--no-build --output $(Build.ArtifactStagingDirectory)/publish -p:Version=$(Build.BuildNumber)'
              command: 'publish'
              projects: 'UmbracoProject/UmbracoProject.csproj'
              publishWebProjects: false
              zipAfterPublish: false
          - task: ArchiveFiles@2
            displayName: 'create build artifact'
            inputs:
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              includeRootFolder: false
              replaceExistingArchive: true
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish/UmbracoProject'
          - task: PublishPipelineArtifact@1
            displayName: 'publish build artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              artifactName: umbraco-build

  - stage: deploy
    displayName: Direct Deploy
    jobs:
      - job:
        displayName: deploy
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'download build artifact'
            inputs:
              artifactName: umbraco-build
              downloadPath: '$(Build.ArtifactStagingDirectory)/deploy'
              downloadType: 'single'
              source: current
          - task: AzureRmWebAppDeployment@4
            displayName: 'deploy artifact'
            inputs:
              AppSettings: '-Umbraco:CMS:Examine:LuceneDirectoryFactory SyncedTempFileSystemDirectoryFactory -Umbraco:CMS:Global:MainDomLock FileSystemMainDomLock -Umbraco:CMS:Hosting:LocalTempStorageLocation EnvironmentTemp'
              appType: webApp
              azureSubscription: 'BrightHR'
              ConnectionType: 'AzureRM'
              deployToSlotOrASE: false
              enableCustomDeployment: true
              package: '$(Build.ArtifactStagingDirectory)/deploy/*.zip'
              resourceGroupName: 'Meetup'
              webAppName: 'umbmeetupstaging'
